### ISSUE TITLE
can't find macos-for-all at intellij startup

### ISSUE THREAD

**Issue by caitsithx** [samvtran/jetbrains-macos-keybindings-for-all#1]
can't find macos-for-all at intellij startup

**Comment by samvtran** [comment]
Thanks for letting me know! It looks like IntelliJ was having issues finding the keymap because of different casing on the plugin name ("For" capitalized) and keymap filename ("for" lowercase).

I've [uploaded a JAR](https://github.com/samvtran/jetbrains-macos-keybindings-for-all/releases/tag/v1.0.1) with the fix if you'd like to test it out. Otherwise, v1.0.1 is currently in the moderation queue on the JetBrains plugin repository. Thanks again!
